import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProviders } from './providers/chakraProviders';
import StoreProvider from './providers/StoreProvider';
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brainspark Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      </head>
      <body>
        <StoreProvider>
          <ChakraProviders>
            {children}
          </ChakraProviders>
        </StoreProvider>
      </body>
    </html>
  );
}
